[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "link-arg=-Wl,--disable-new-dtags",
  "-C", "link-arg=-Wl,-rpath,$ORIGIN",
  "-C", "link-arg=-Wl,-rpath,$ORIGIN/../lib/dorion",
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
  "-C", "link-arg=-Wl,--disable-new-dtags",
  "-C", "link-arg=-Wl,-rpath,$ORIGIN",
  "-C", "link-arg=-Wl,-rpath,$ORIGIN/../lib/dorion",
]