name: Publish to WinGet Package Repository

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Extract version
        id: extract-ver
        run: |
          $VER="${{ github.event.release.tag_name }}"
          $SEMVER=$VER.Substring(1)
          echo "SEMVER=$SEMVER" >> $env:GITHUB_OUTPUT

      - uses: vedantmgoyal9/winget-releaser@19e706d4c9121098010096f9c495a70a7518b30f
        with:
          identifier: SpikeHD.Dorion
          version: ${{ steps.extract-ver.outputs.SEMVER }}
          token: ${{ secrets.WINGET_TOKEN }}
